[package]
name = "usaddress-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
usaddress = {path="../usaddress-lib"}
serde_json = "1.0"
lazy_static = "1.4"
